# Site settings
title: Dylan Bernard
name: Dylan Bernard's Personal Site
email: dtbernard11@gmail.com
description:
    The personal website of Dylan Bernard - blog posts about Computer Science
    and Software Engineering
#url: "https://dylanbernard.com"

# Build settings
markdown: kramdown
