# Site settings
title: Dylan Bernard
email: dtbernard11@gmail.com
description:
    The personal website of Dylan Bernard - blog posts about Computer Science
    and Software Engineering
url: "http://dylanbernard.com"

# Build settings
markdown: kramdown
